# Do not change this (Only for internal use)!
config-version: 1.2

# If set to true, players will experience hunger. If set to false, players won't experience hunger.
# This option allows you to enable or disable the hunger mechanic for players in the server.
hunger: true

# The message displayed when a player attempts to eat a restricted food item.
# You can use color codes by using "ยง" or "&" before the color code.
# This message will be shown to players when they try to eat an item that is restricted based on the configuration.
message: "&cYou can't eat your food here"

# Item Restriction Settings
items:
  # List of food items that players are not allowed to eat.
  # This list determines which food items are restricted for consumption by players.
  list:
    - "golden_apple"
    - "cooked_beef"
    - "cooked_chicken"

# World Restriction Settings
worlds:
  # The mode can be either "blacklist," "whitelist," or "none".
  # - "blacklist" mode will prevent players from eating in the specified worlds (blacklisted) and allow eating in other worlds.
  # - "whitelist" mode will only allow players to eat in the specified worlds (whitelisted) and prevent eating in other worlds.
  # - "none" mode will not apply any restrictions, and eating will be allowed in all worlds.
  mode: "blacklist"

  # List of world folder names to be blacklisted or whitelisted (depending on the mode set above).
  # If "mode" is set to "blacklist" or "whitelist," add the world folder names accordingly.
  # If "mode" is set to "none," leave the "list" empty ([]) to allow eating in all worlds.
  list:
    - "world"  # Example: The "world" world folder is blacklisted, and players can't eat here.
    - "world_nether"  # Example: The "world_nether" world folder is blacklisted, and players can't eat here.

# You can add more worlds to the list as needed.
# Note: Make sure to use the correct world folder names as specified in your PocketMine-MP server configuration.
# To disable world-specific eating restriction and allow eating in all worlds, set "mode" to "none" and leave the "list" empty ([]) or remove the "list" entirely.
