---
# Do not change this (Only for internal use)!
config-version: 1.0

# If you want to activate player hunger.
hunger: true

# Message used when canceling a player who ate food.
# Use "ยง" or "&" to color the message.
message: "&cYou can't eat your food here"

items:
  # List of items that can't be eat.
  # This must be food to work.
  # If the item has meta, you can use the format "minecraft:id:meta".
  list:
    - "minecraft:golden_apple"
    - "minecraft:cooked_beef"
    - "minecraft:cooked_chicken"

worlds:
  # The mode can be either "blacklist" or "whitelist".
  # The blacklist mode will only cancel players to eat and players to be hungry according to the name of a predetermined world folder and will allow player feeding and hunger players around the world.
  # The whitelist mode will only allow players to eat and players to be hungry according to the name of a predetermined world folder and will cancel player feeding and starve players around the world.
  mode: "blacklist"
  # List of world folder names to blacklist/whitelist (depending on the mode set above).
  # Leave it blank if you want to let players eat all over the world.
  list:
    - "world"
...
